# Generated by Django 5.0 on 2026-01-04 08:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order for display (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='brandmenu',
            options={'ordering': ['category', 'name']},
        ),
        migrations.AddField(
            model_name='brandmenu',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brandmenu',
            name='image',
            field=models.ImageField(blank=True, help_text='Menu item image', null=True, upload_to='menus/'),
        ),
        migrations.AddField(
            model_name='brandmenu',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='brandmenu',
            name='category',
            field=models.ForeignKey(blank=True, default=None, help_text='Category this menu item belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menus', to='menus.category'),
        ),
    ]
