# Generated by Django 5.0 on 2026-01-04 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_category_alter_brandmenu_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuantityUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unit name (e.g., kg, pieces, plates)', max_length=50, unique=True)),
                ('abbreviation', models.CharField(help_text='Abbreviation (e.g., kg, pcs, plates)', max_length=10, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the unit')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order for display')),
            ],
            options={
                'verbose_name': 'Quantity Unit',
                'verbose_name_plural': 'Quantity Units',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='brandmenu',
            name='quantity_value',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Quantity value (e.g., 1, 500, 2.5)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='brandmenu',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category this menu item belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menus', to='menus.category'),
        ),
        migrations.AddField(
            model_name='brandmenu',
            name='quantity_unit',
            field=models.ForeignKey(blank=True, help_text='Unit of measurement (e.g., kg, pieces, plates)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menus', to='menus.quantityunit'),
        ),
    ]
