# Generated by Django 5.0 on 2026-01-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_quantityunit_brandmenu_quantity_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantityunit',
            name='measurement_category',
            field=models.CharField(blank=True, choices=[('WEIGHT', 'Weight'), ('VOLUME', 'Volume'), ('COUNT', 'Count'), ('SERVING', 'Serving')], help_text='Category of measurement (Weight, Volume, Count, Serving)', max_length=10, null=True),
        ),
    ]
