# Generated by Django 5.0 on 2026-01-11 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0004_quantityunit_measurement_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandmenu',
            name='quantity_unit',
        ),
        migrations.RemoveField(
            model_name='brandmenu',
            name='quantity_value',
        ),
        migrations.DeleteModel(
            name='QuantityUnit',
        ),
    ]
